import heapq
from typing import List
from utils_files.cell import Cell
from utils_files.data import Data


def get_dijkstra_neighbors(
        grid: List[List[Cell]],
        cell: Cell,
        parsed: NamedTuple) -> List[Cell]:
	"""
    Checking which cell is available to move in

    Args:
        grid: The maze generated by wilson's algorithm
		cell: the cell whose walls are being encoded
		parsed: All the parsed data from the config.txt file

    Returns:
        Available cells to move in
    """
    neighbors = []
    x, y = cell.x, cell.y
    if not cell.walls['N'] and y > 0:
        neighbors.append(grid[x][y - 1])
    if not cell.walls['S'] and y < parsed.height - 1:
        neighbors.append(grid[x][y + 1])
    if not cell.walls['E'] and x < parsed.width - 1:
        neighbors.append(grid[x + 1][y])
    if not cell.walls['W'] and x > 0:
        neighbors.append(grid[x - 1][y])
    return neighbors


def solve_dijkstra(
        grid: List[List[Cell]],
        parsed: NamedTuple) -> List[Cell]:
    """
	Calulate the shortest path from entry to exit
	
	Args:
		cell: the cell whose walls are being encoded
		parsed: All the parsed data from the config.txt file
	
	Return:
		The shortest path from entry to exit
	"""
    start_cell = grid[parsed.entry[0]][parsed.entry[1]]
    end_cell = grid[parsed.exit_[0]][parsed.exit_[1]]
    distances: Dict[Tuple[int, int], float] = {
        (c.x, c.y): float('inf') for row in grid for c in row
    }
    predecessors: Dict[Cell, Cell] = {}
    distances[(start_cell.x, start_cell.y)] = 0
    queue: List[Tuple[float, int, int]] = [(0.0, start_cell.x, start_cell.y)]
    while queue:
        current_dist, x, y = heapq.heappop(queue)
        current = grid[x][y]
        if current == end_cell:
            break
        if current_dist > distances[(x, y)]:
            continue
        for neighbor in get_dijkstra_neighbors(grid, current, parsed):
            new_dist = current_dist + 1
            if new_dist < distances[(neighbor.x, neighbor.y)]:
                distances[(neighbor.x, neighbor.y)] = new_dist
                predecessors[neighbor] = current
                heapq.heappush(queue, (new_dist, neighbor.x, neighbor.y))
    path: List[Cell] = []
    if end_cell in predecessors or end_cell == start_cell:
        curr: Cell = end_cell
        while curr in predecessors:
            path.append(curr)
            curr = predecessors[curr]
        path.append(start_cell)
        path.reverse()
    return path


def mark_path_in_matrix(
        matrix: List[List[str]],
        path: List[Cell],
        parsed: Data) -> None:
    for i in range(len(path)):
        cell = path[i]
        rx, ry = cell.x * 2 + 1, cell.y * 2 + 1
        matrix[ry][rx] = "."
    for curr, nxt in zip(path, path[1:]):
        mid_x = (curr.x * 2 + 1 + nxt.x * 2 + 1) // 2
        mid_y = (curr.y * 2 + 1 + nxt.y * 2 + 1) // 2
        matrix[mid_y][mid_x] = "."
    entry_x, entry_y = parsed.entry
    exit_x, exit_y = parsed.exit_
    matrix[entry_y * 2 + 1][entry_x * 2 + 1] = "M"
    matrix[exit_y * 2 + 1][exit_x * 2 + 1] = "N"
