import random
import sys
import subprocess
from errors import exit_program
from typing import List, Tuple, Dict, NamedTuple
from utils_files.pattern import PATTERN_SANS, get_pattern_by_name
from utils_files.themes import get_bg_list_for_pattern
from algorithms.dijkstra import solve_dijkstra, mark_path_in_matrix
from algorithms.gen_output import write_output_file
from utils_files.cell import Cell


current_bg_list: List[str] = []


def is_obstacle(cell: Cell) -> bool:
    """
	Check if the cell is part of the symbol or a wall

	Args:
		cell: the cell whose walls are being encoded
	
	Return:
		True or False if the cell has to be considered as an obstacle
	"""
    return cell.is_blocked or cell.in_symbol or cell.sans_eye


def remove_wall(
        cell1: Cell,
        cell2: Cell) -> None:
    """
	This function is used to remove a wall between two cells
	
	Args:
		cell1: The starting cell
        cell2: The adjacent cell
	"""
    dx = cell2.x - cell1.x
    dy = cell2.y - cell1.y
    if dx == 1:
        cell1.walls['E'] = False
        cell2.walls['W'] = False
    elif dx == -1:
        cell1.walls['W'] = False
        cell2.walls['E'] = False
    elif dy == 1:
        cell1.walls['S'] = False
        cell2.walls['N'] = False
    elif dy == -1:
        cell1.walls['N'] = False
        cell2.walls['S'] = False


def non_perfect(
        grid: List[List[Cell]],
        parsed: NamedTuple,
        ratio: float = 0.15) -> None:
    """
	This function break random wall in the maze already generated
    to make it 'non-perfect'
	
	Args:
		grid: The maze generated by wilson's algorithm
		parsed: All the parsed data from the config.txt file
	"""
    remove_walls: List[Tuple[Cell, Cell]] = []
    for x in range(parsed.parsed.width):
        for y in range(parsed.parsed.height):
            cell = grid[x][y]
            if is_obstacle(cell):
                continue
            if cell.walls['E'] and x + 1 < parsed.parsed.width:
                neighbor = grid[x + 1][y]
                if not is_obstacle(neighbor):
                    remove_walls.append((cell, neighbor))
            if cell.walls['S'] and y + 1 < parsed.parsed.height:
                neighbor = grid[x][y + 1]
                if not is_obstacle(neighbor):
                    remove_walls.append((cell, neighbor))
    num_to_remove = int(len(remove_walls) * ratio)
    walls_to_remove = random.sample(
        remove_walls,
        min(num_to_remove, len(remove_walls))
    )
    for cell1, cell2 in walls_to_remove:
        remove_wall(cell1, cell2)


def apply_pattern(
        grid: List[List[Cell]],
        parsed: NamedTuple,
        pattern: str) -> bool:
    """
	This function will pregenerate the pattern within the maze's edge
	

	Args:
		grid: The maze generated by wilson's algorithm
		parsed: All the parsed data from the config.txt file
		pattern: The pattern's name created in the pattern.py file
	
	Return:
		A tuple with a boolean if the sans. pattern is used, and the list
		of the complete list of pattern from the themes.py file

	"""
    pattern_matrix = get_pattern_by_name(pattern)
    is_sans = (pattern_matrix == PATTERN_SANS)
    bg_list = get_bg_list_for_pattern(is_sans)
    if parsed.width < 10 or parsed.height < 10:
        return is_sans, bg_list
    pat_h, pat_w = len(pattern_matrix), len(pattern_matrix[0])
    start_x = (parsed.width - pat_w) // 2
    start_y = (parsed.height - pat_h) // 2
    for py in range(pat_h):
        for px in range(pat_w):
            val = pattern_matrix[py][px]
            target = grid[start_x + px][start_y + py]
            if val == 1:
                target.is_blocked = True
            elif val == 2:
                target.in_symbol = True
            elif val == 3:
                target.sans_eye = True
    return is_sans, bg_list


def get_unblocked_neighbors(
        grid: List[List[Cell]],
        cell: Cell,
        parsed: NamedTuple) -> List[Cell]:
    """
	Get the whole list of the available cell to move in

	Args:
		grid: The maze generated by wilson's algorithm
		cell: the cell whose walls are being encoded
		parsed: All the parsed data from the config.txt file
	
	Return:
		The list of the cells that are not obstacles
	"""
    neighbors = []
    for dx, dy in [(0, -1), (1, 0), (0, 1), (-1, 0)]:
        nx, ny = cell.x + dx, cell.y + dy
        if (
                0 <= nx < parsed.width
                and 0 <= ny < parsed.height
                and not is_obstacle(grid[nx][ny])):
            neighbors.append(grid[nx][ny])
    return neighbors


def generate_wilson(
        pattern: str,
        parsed: NamedTuple) -> List[List[Cell]]:
    """
    Generate the whole maze using the Wilson's Algorithm
	
	Args:
		parsed: All the parsed data from the config.txt file
		pattern: The pattern's name created in the pattern.py file
	
	Return:
		The list that represent the maze
	"""
    grid = [[Cell(x, y) for y in range(parsed.height)] for x in range(parsed.width)]
    is_sans, bg_list = apply_pattern(grid, parsed.width, parsed.height, pattern)
    unvisited = [
        grid[x][y] for x in range(parsed.width)
        for y in range(parsed.height)
        if not is_obstacle(grid[x][y])]
    if not unvisited:
        return grid, is_sans, bg_list
    first_cell = random.choice(unvisited)
    unvisited.remove(first_cell)
    while unvisited:
        current = random.choice(unvisited)
        path = [current]
        while current in unvisited:
            neighbors = get_unblocked_neighbors(grid, current, parsed.width, parsed.height)
            current = random.choice(neighbors)
            if current in path:
                path = path[:path.index(current) + 1]
            else:
                path.append(current)
        for i in range(len(path) - 1):
            remove_wall(path[i], path[i + 1])
            if path[i] in unvisited:
                unvisited.remove(path[i])
    if not parsed.perfect:
        non_perfect(grid, parsed)
    return grid, is_sans, bg_list


def build_matrix_1x1(
        grid: List[List[Cell]],
        parsed: NamedTuple,
        is_sans: bool = False) -> Tuple[List[List[str]], int, int]:
    """
	This function build the maze matrix with characters
	
	Args:
		grid: The maze generated by wilson's algorithm
		parsed: All the parsed data from the config.txt file
		is_sans: A boolean to check if the sans. pattern is used
	
	Return:
		A tuple of a list of a list of str, this is the maze's matrix
		that will be used in the render, and two int that are the
		render width and height
	"""
    render_w = parsed.width * 2 + 1
    render_h = parsed.height * 2 + 1
    maze_matrix = [["W" for _ in range(render_w)] for _ in range(render_h)]
    for x in range(parsed.width):
        for y in range(parsed.height):
            cell = grid[x][y]
            rx, ry = x * 2 + 1, y * 2 + 1

            if cell.is_blocked:
                maze_matrix[ry][rx] = "B"
            elif cell.in_symbol:
                maze_matrix[ry][rx] = "C"
            elif cell.sans_eye:
                maze_matrix[ry][rx] = "I"
            else:
                maze_matrix[ry][rx] = " "
                if not cell.walls['E']:
                    maze_matrix[ry][rx + 1] = " "
                if not cell.walls['S']:
                    maze_matrix[ry + 1][rx] = " "
    if is_sans:
        _merge_sans_blocks(grid, maze_matrix, parsed)
    return maze_matrix, render_w, render_h


def _merge_sans_blocks(
        grid: List[List[Cell]],
        maze_matrix: List[List[str]],
        parsed: NamedTuple,) -> None:
    """
	Special fuction that merge the walls inside of the sans. pattern
	
	Args:
		grid: The maze generated by wilson's algorithm
		maze_matrix: The matrix of the maze
		parsed: All the parsed data from the config.txt file
	"""
    for x in range(parsed.width):
        for y in range(parsed.height):
            cell = grid[x][y]
            if is_obstacle(cell):
                rx, ry = x * 2 + 1, y * 2 + 1
                if cell.is_blocked:
                    char = "W"
                else:
                    if cell.sans_eye:
                        char = "I"
                    else:
                        char = "C"
                maze_matrix[ry][rx] = char
                maze_matrix[ry][rx + 1] = char
                maze_matrix[ry + 1][rx] = char
                maze_matrix[ry + 1][rx + 1] = char

                if x + 1 < parsed.width and (
                    (cell.is_blocked and grid[x + 1][y].is_blocked)
                    or (cell.in_symbol and grid[x + 1][y].in_symbol)
                    or (cell.sans_eye and grid[x + 1][y].sans_eye)
                ):
                    maze_matrix[ry][rx + 2] = char
                    maze_matrix[ry + 1][rx + 2] = char

                if y + 1 < parsed.height and (
                    (cell.is_blocked and grid[x][y + 1].is_blocked)
                    or (cell.in_symbol and grid[x][y + 1].in_symbol)
                    or (cell.sans_eye and grid[x][y + 1].sans_eye)
                ):
                    maze_matrix[ry + 2][rx] = char
                    maze_matrix[ry + 2][rx + 1] = char


def render_terminal_blocks(
        matrix: List[List[str]],
        render_w: int,
        render_h: int,
        bg_list: List[str]) -> None:
    """
	The rendering the maze using ANSI code, with the color palette
	selected in the themes.py file

	Args:
		matrix: The matrix of the maze
		render_w: The width of the character rendered
		render_h: The height of the character rendered
		bg_list: The different color theme from the themes.py file
    """
    color_map: Dict[str, str] = {
        "W": bg_list[0],
        "B": bg_list[1],
        "C": bg_list[2],
        "I": "\033[48;2;71;130;201m",
        ".": bg_list[4],
        "M": "\033[48;2;60;115;210m",
        "N": "\033[48;2;210;120;20m",
    }
    default_color = bg_list[3]
    reset_code = "\033[0m"
    for y in range(render_h):
        line = "".join(
            f"{color_map.get(matrix[y][x], default_color)}  {reset_code}"
            for x in range(render_w)
        )
        print(line)


def run_session(
		parsed: NamedTuple,
		new_gen: Tuple[List[List[str]], int, int, bool, List[str]]) -> None:
    matrix, r_w, r_h, is_sans, bg_list = new_gen
    theme_index: int = 0
    show_path: bool = True
    try:
        while True:
            print("1 - Re-generate Maze")
            print("2 - Show/hide path")
            print("3 - Change colour")
            print("q - Quit")
            choice = input("Select an option: ")
            if choice == "1":
                matrix, r_w, r_h, is_sans, _ = wilson_main(parsed)
                bg_list = get_bg_list_for_pattern(is_sans, theme_index)
            elif choice == "2":
                show_path = not show_path
            elif choice == "3":
                theme_index += 1
                bg_list = get_bg_list_for_pattern(is_sans, theme_index)
            elif choice == "q":
                sys.exit(0)
            else:
                continue
            temp: List[str] = bg_list.copy()
            if not show_path:
                temp[4] = temp[3]
            subprocess.run("clear")
            render_terminal_blocks(matrix, r_w, r_h, temp)
    except (EOFError, KeyboardInterrupt):
        exit_program("Exiting program properly.")


def wilson_main(parsed: NamedTuple) -> Tuple[List[List[str]], int, int, bool, List[str]]:
    maze, is_sans, bg_list = generate_wilson(pattern, parsed)
    matrix, r_w, r_h = build_matrix_1x1(maze, parsed, is_sans=is_sans)
    path = solve_dijkstra(maze, parsed)
    mark_path_in_matrix(matrix, path, parsed)
    render_terminal_blocks(matrix, r_w, r_h, bg_list)
    write_output_file(parsed.output_file, parsed.entry, parsed.exit_, maze, path)
    return matrix, r_w, r_h, is_sans, bg_list
