from .cell import Cell
from typing import List
import random


def remove_wall(cell1: Cell,
                cell2: Cell) -> None:
    """
    This function is used to remove a wall between two cells

    Args:
        cell1: The starting cell
        cell2: The adjacent cell
    """
    dx = cell2.x - cell1.x
    dy = cell2.y - cell1.y
    if dx == 1:
        cell1.walls['E'] = False
        cell2.walls['W'] = False
    elif dx == -1:
        cell1.walls['W'] = False
        cell2.walls['E'] = False
    elif dy == 1:
        cell1.walls['S'] = False
        cell2.walls['N'] = False
    elif dy == -1:
        cell1.walls['N'] = False
        cell2.walls['S'] = False


def get_unblocked_neighbors(grid: List[List[Cell]],
                            cell: Cell,
                            width: int,
                            height: int) -> List[Cell]:
    """
    Get the whole list of the available cell to move in

    Args:
        grid: The maze generated by wilson's algorithm
        cell: the cell whose walls are being encoded
        height: The height of the maze
        width: The width of the maze

    Return:
        The list of the cells that are not obstacles
    """
    neighbors = []
    for dx, dy in [(0, -1), (1, 0), (0, 1), (-1, 0)]:
        nx, ny = cell.x + dx, cell.y + dy
        if (
                0 <= nx < width
                and 0 <= ny < height
                and not grid[nx][ny].is_blocked):
            neighbors.append(grid[nx][ny])
    return neighbors


def generate_wilson(grid: List[List[Cell]],
                    width: int,
                    height: int,
                    rng: random.Random) -> None:
    """
    Carves a perfect maze into the grid using Wilson's algorithm
    (loop-erased random walk), skipping cells marked is_blocked.

    Args:
        grid: the grid of Cells to carve into (already built,
            with the 42 pattern already applied if any).
        width: the maze's width in cells.
        height: the maze's height in cells.
        rng: the seeded random generator to use for all randomness.
    """
    # Real cells not yet connected to the maze.
    unvisited = [
        grid[x][y] for x in range(width)
        for y in range(height)
        if not grid[x][y].is_blocked
    ]
    if not unvisited:
        return

    # Seed the maze with one arbitrary starting cell.
    first_cell = rng.choice(unvisited)
    unvisited.remove(first_cell)

    while unvisited:
        # Random walk from an unvisited cell until it hits the maze.
        current = rng.choice(unvisited)
        path = [current]

        while current in unvisited:
            neighbors = get_unblocked_neighbors(grid, current, width, height)
            current = rng.choice(neighbors)

            if current in path:
                # Loop-erase: cut back to the earlier visit.
                path = path[:path.index(current) + 1]
            else:
                path.append(current)

        # Carve the loop-erased path into the maze.
        for i in range(len(path) - 1):
            remove_wall(path[i], path[i + 1])
            if path[i] in unvisited:
                unvisited.remove(path[i])


def non_perfect(grid: List[List[Cell]],
                width: int,
                height: int) -> None:
    """
    Removes dead-ends from the maze by repeatedly breaking one wall
    per 3-walled cell, until no dead-ends remain among real
    (non-pattern) cells.

    Args:
        grid: the grid of Cells, already carved into a perfect maze
            by generate_wilson.
        width: the maze's width in cells.
        height: the maze's height in cells.
    """
    directions = [(0, -1), (1, 0), (0, 1), (-1, 0)]

    def open_count(cell: Cell) -> int:
        return sum(not closed for closed in cell.walls.values())

    changed = True
    while changed:
        changed = False
        for x in range(width):
            for y in range(height):
                cell = grid[x][y]
                if cell.is_blocked or open_count(cell) != 1:
                    continue
                for dx, dy in directions:
                    nx, ny = cell.x + dx, cell.y + dy
                    if not (0 <= nx < width
                            and 0 <= ny < height):
                        continue
                    neighbor = grid[nx][ny]
                    if neighbor.is_blocked:
                        continue
                    wall_dir = {(0, -1): 'N', (1, 0): 'E',
                                (0, 1): 'S', (-1, 0): 'W'}[(dx, dy)]
                    if not cell.walls[wall_dir]:
                        continue
                    remove_wall(cell, neighbor)
                    changed = True
                    break
