from .cell import Cell
from typing import List, Tuple, Dict, Optional
from collections import deque
import random


def remove_wall(cell1: Cell,
                cell2: Cell) -> None:
    """
    This function is used to remove a wall between two cells

    Args:
        cell1: The starting cell
        cell2: The adjacent cell
    """
    dx = cell2.x - cell1.x
    dy = cell2.y - cell1.y
    if dx == 1:
        cell1.walls['E'] = False
        cell2.walls['W'] = False
    elif dx == -1:
        cell1.walls['W'] = False
        cell2.walls['E'] = False
    elif dy == 1:
        cell1.walls['S'] = False
        cell2.walls['N'] = False
    elif dy == -1:
        cell1.walls['N'] = False
        cell2.walls['S'] = False


def get_unblocked_neighbors(grid: List[List[Cell]],
                            cell: Cell,
                            width: int,
                            height: int) -> List[Cell]:
    """
    Get the whole list of the available cell to move in

    Args:
        grid: The maze generated by wilson's algorithm
        cell: the cell whose walls are being encoded
        height: The height of the maze
        width: The width of the maze

    Return:
        The list of the cells that are not obstacles
    """
    neighbors = []
    for dir_x, dir_y in [(0, -1), (1, 0), (0, 1), (-1, 0)]:
        neighbor_x, neighbor_y = cell.x + dir_x, cell.y + dir_y
        if (
                0 <= neighbor_x < width
                and 0 <= neighbor_y < height
                and not grid[neighbor_x][neighbor_y].is_blocked):
            neighbors.append(grid[neighbor_x][neighbor_y])
    return neighbors


def generate_wilson(grid: List[List[Cell]],
                    width: int,
                    height: int,
                    rng: random.Random) -> None:
    """
    Carves a perfect maze into the grid using Wilson's algorithm
    (loop-erased random walk), skipping cells marked is_blocked.

    Args:
        grid: the grid of Cells to carve into (already built,
              with the 42 pattern already applied if any).
        width: the maze's width in cells.
        height: the maze's height in cells.
        rng: the seeded random generator to use for all randomness.
    """
    # Real cells not yet connected to the maze.
    unvisited = [
        grid[x][y] for x in range(width)
        for y in range(height)
        if not grid[x][y].is_blocked
    ]
    if not unvisited:
        return

    # Seed the maze with one arbitrary starting cell.
    first_cell = rng.choice(unvisited)
    unvisited.remove(first_cell)

    while unvisited:
        # Random walk from an unvisited cell until it hits the maze.
        current = rng.choice(unvisited)
        path = [current]

        while current in unvisited:
            neighbors = get_unblocked_neighbors(grid, current, width, height)
            current = rng.choice(neighbors)

            if current in path:
                # Loop-erase: cut back to the earlier visit.
                path = path[:path.index(current) + 1]
            else:
                path.append(current)

        # Carve the loop-erased path into the maze.
        for i in range(len(path) - 1):
            remove_wall(path[i], path[i + 1])
            if path[i] in unvisited:
                unvisited.remove(path[i])


def non_perfect(grid: List[List[Cell]],
                width: int,
                height: int) -> None:
    """
    Removes dead-ends from the maze by repeatedly breaking one wall
    per 3-walled cell, until no dead-ends remain among real
    (non-pattern) cells.

    Args:
        grid: the grid of Cells, already carved into a perfect maze
              by generate_wilson.
        width: the maze's width in cells.
        height: the maze's height in cells.
    """
    directions = [(0, -1), (1, 0), (0, 1), (-1, 0)]

    def open_count(cell: Cell) -> int:
        return sum(not closed for closed in cell.walls.values())

    changed = True
    while changed:
        changed = False
        for x in range(width):
            for y in range(height):
                cell = grid[x][y]
                if cell.is_blocked or open_count(cell) != 1:
                    continue
                for dir_x, dir_y in directions:
                    neighbor_x, neighbor_y = cell.x + dir_x, cell.y + dir_y
                    if not (0 <= neighbor_x < width
                            and 0 <= neighbor_y < height):
                        continue
                    neighbor = grid[neighbor_x][neighbor_y]
                    if neighbor.is_blocked:
                        continue
                    wall_dir = {(0, -1): 'N', (1, 0): 'E',
                                (0, 1): 'S', (-1, 0): 'W'}[(dir_x, dir_y)]
                    if not cell.walls[wall_dir]:
                        continue
                    remove_wall(cell, neighbor)
                    changed = True
                    break


def _walkable_neighbors(cell: Cell,
                        grid: List[List[Cell]],
                        width: int,
                        height: int) -> List[Cell]:
    """
    Finds the neighboring cells reachable from a cell through an
    already-open wall. Pathfinding through a fully
    generated maze, unlike get_unblocked_neighbors, which is used
    during generation and ignores wall state entirely.

    Args:
        cell: the cell to find walkable neighbors from.
        grid: the fully generated grid of Cells.
        width: the maze's width in cells.
        height: the maze's height in cells.

    Returns:
        The list of neighboring cells connected to `cell` by an
        open wall.
    """
    neighbors = []
    for dir_x, dir_y in [(0, -1), (1, 0), (0, 1), (-1, 0)]:
        neighbor_x, neighbor_y = cell.x + dir_x, cell.y + dir_y
        wall_dir = {(0, -1): 'N', (1, 0): 'E',
                    (0, 1): 'S', (-1, 0): 'W'}[(dir_x, dir_y)]
        if (0 <= neighbor_x < width and 0 <= neighbor_y < height):
            if cell.walls[wall_dir]:
                continue
            else:
                neighbors.append(grid[neighbor_x][neighbor_y])
    return neighbors


def bfs(grid: List[List[Cell]],
        width: int,
        height: int,
        start: Tuple[int, int],
        end: Tuple[int, int]) -> List[Cell]:
    """
    Finds the shortest path between two cells in a fully generated
    maze using breadth-first search.

    Args:
        grid: the fully generated grid of Cells.
        width: the maze's width in cells.
        height: the maze's height in cells.
        start: the starting coordinates (x, y).
        end: the target coordinates (x, y).

    Returns:
        The shortest path from start to end, as a list of Cell,
        in order from start to end (inclusive of both).
    """
    queue = deque()
    start_cell: Cell = grid[start[0]][start[1]]
    end_cell: Cell = grid[end[0]][end[1]]
    came_from: Dict[Cell, Optional[Cell]] = {}
    came_from[start_cell] = None
    queue.append(start_cell)
    while queue:
        current = queue.popleft()
        if current == end_cell:
            break
        else:
            neighbors = _walkable_neighbors(current, grid, width, height)
            for neighbor in neighbors:
                if neighbor in came_from:
                    continue
                else:
                    came_from[neighbor] = current
                queue.append(neighbor)
    res: List[Cell] = []
    current = end_cell
    while current is not None:
        res.append(current)
        current = came_from[current]
    res.reverse()
    return res
